### PR TITLE
python3-jetson-stats: update to 4.2.4

### LINKED ISSUE #129: python3-jetson-stats: update for JP6 compatibility
Hello, 

The current 4.2.3 version of python3-jetson-stats is not compatible with JP6.0.

Do you plan to update version to the latest one ?

Thanks

### PR DESCRIPTION
**Pull request by spencercw**
Fixes #129.

### CODE REVIEW

**Comment by ichergui** [comment]
Thanks @spencercw for this PR. 
Which branch did you use for testing ?

**Comment by spencercw** [comment]
I tested on poky `scarthgap`, but for the purposes of this PR I used the meta-tegra-community `master` branch and changed `styhead` to `scarthgap` in `conf/layer.conf`.

**Comment by spencercw** [comment]
Thanks for merging. I'd like to backport this to `scarthgap` if possible. Should I just create a new PR with the same changes on the `scarthgap` branch?

**Comment by ichergui** [comment]
I will do that @spencercw

**Comment by spencercw** [comment]
Great, thank you

**Comment by ichergui** [comment]
You're welcome

**Pull request merged**
